import { readdir, readFile, writeFile } from 'node:fs/promises';
import path from 'node:path';
import process from 'node:process';
import { fileURLToPath } from 'node:url';
import { parseDocument } from 'yaml';
import { format, resolveConfig } from 'prettier';

const projectRoot = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const localeDirectory = path.join(projectRoot, 'locales');
const generatedCatalogPath = path.join(projectRoot, 'src', 'shared', 'generated-i18n.ts');
const publicLocaleDirectory = path.join(projectRoot, 'public', '_locales');
const checkOnly = process.argv.includes('--check');

const localeFiles = (await readdir(localeDirectory))
  .filter((filename) => filename.endsWith('.yml'))
  .sort();
const locales = Object.fromEntries(
  await Promise.all(
    localeFiles.map(async (filename) => {
      const locale = filename.slice(0, -'.yml'.length);
      return [
        locale,
        parseLocaleFile(filename, await readFile(path.join(localeDirectory, filename), 'utf8')),
      ];
    }),
  ),
);

if (locales.en === undefined) throw new Error('locales/en.yml is required as the source locale.');
validateCatalogs(locales);

const prettierConfig = await resolveConfig(generatedCatalogPath);
const spoilerLabelTerms = [
  ...new Set(Object.values(locales).flatMap((value) => value.discord.spoiler_label_terms)),
];
const generatedCatalog = await format(
  `${'// This file is generated by scripts/generate-i18n.mjs. Do not edit it directly.\n'}export const catalogs = ${JSON.stringify(
    Object.fromEntries(Object.entries(locales).map(([locale, value]) => [locale, value.messages])),
    null,
    2,
  )} as const;\n\nexport const discordSpoilerLabelTerms = ${JSON.stringify(
    spoilerLabelTerms,
    null,
    2,
  )} as const;\n\nexport type GeneratedLocale = keyof typeof catalogs;\nexport type GeneratedTranslationKey = keyof typeof catalogs.en;\n`,
  { ...prettierConfig, filepath: generatedCatalogPath },
);

await emitFile(generatedCatalogPath, generatedCatalog);
for (const [locale, value] of Object.entries(locales)) {
  const manifestMessages = `${JSON.stringify(
    {
      extension_name: { message: value.manifest.extension_name },
      extension_description: { message: value.manifest.extension_description },
    },
    null,
    2,
  )}\n`;
  await emitFile(
    path.join(publicLocaleDirectory, chromeLocaleName(locale), 'messages.json'),
    manifestMessages,
  );
}

if (!checkOnly) console.log(`Generated ${Object.keys(locales).length} locale catalogs.`);

function parseLocaleFile(filename, source) {
  const document = parseDocument(source, { uniqueKeys: true });
  if (document.errors.length > 0) {
    throw new Error(`${filename}: ${document.errors.map((error) => error.message).join('; ')}`);
  }
  const value = document.toJS();
  if (
    !isRecord(value) ||
    Object.keys(value).sort().join(',') !== 'discord,manifest,messages' ||
    !isRecord(value.manifest) ||
    !isRecord(value.discord) ||
    !isRecord(value.messages)
  ) {
    throw new Error(`${filename}: expected only discord, manifest, and messages mappings.`);
  }
  const manifestKeys = Object.keys(value.manifest).sort();
  if (manifestKeys.join(',') !== 'extension_description,extension_name') {
    throw new Error(
      `${filename}: manifest must contain only extension_name and extension_description.`,
    );
  }
  if (!stringRecord(value.manifest) || !stringRecord(value.messages)) {
    throw new Error(`${filename}: manifest and message values must be non-empty strings.`);
  }
  if (
    Object.keys(value.discord).join(',') !== 'spoiler_label_terms' ||
    !Array.isArray(value.discord.spoiler_label_terms) ||
    value.discord.spoiler_label_terms.length === 0 ||
    value.discord.spoiler_label_terms.length > 20
  ) {
    throw new Error(`${filename}: discord.spoiler_label_terms must contain 1-20 terms.`);
  }
  const spoilerLabelTerms = value.discord.spoiler_label_terms.map((term) => {
    if (typeof term !== 'string') {
      throw new Error(`${filename}: each spoiler label term must be a string.`);
    }
    const normalized = term.normalize('NFKC').toLowerCase().trim();
    if (normalized.length === 0 || normalized.length > 80) {
      throw new Error(`${filename}: each spoiler label term must contain 1-80 characters.`);
    }
    return normalized;
  });
  if (new Set(spoilerLabelTerms).size !== spoilerLabelTerms.length) {
    throw new Error(`${filename}: spoiler label terms must be unique within a locale.`);
  }
  return {
    manifest: value.manifest,
    discord: { spoiler_label_terms: spoilerLabelTerms },
    messages: value.messages,
  };
}

function validateCatalogs(localesToValidate) {
  const sourceKeys = Object.keys(localesToValidate.en.messages).sort();
  for (const [locale, value] of Object.entries(localesToValidate)) {
    const keys = Object.keys(value.messages).sort();
    if (keys.join('\n') !== sourceKeys.join('\n')) {
      throw new Error(`${locale}: message keys do not match the English source catalog.`);
    }
    for (const key of sourceKeys) {
      const expected = placeholders(localesToValidate.en.messages[key]);
      const actual = placeholders(value.messages[key]);
      if (actual.join('\n') !== expected.join('\n')) {
        throw new Error(
          `${locale}.${key}: placeholders must match English (${expected.join(', ')}).`,
        );
      }
    }
  }
}

function placeholders(message) {
  return [...message.matchAll(/\{([A-Za-z][A-Za-z0-9]*)\}/g)].map((match) => match[1]).sort();
}

async function emitFile(filename, content) {
  if (checkOnly) {
    const current = await readFile(filename, 'utf8').catch(() => null);
    if (current !== content) {
      throw new Error(`${path.relative(projectRoot, filename)} is stale. Run pnpm i18n:generate.`);
    }
    return;
  }
  await writeFile(filename, content, 'utf8');
}

function isRecord(value) {
  return typeof value === 'object' && value !== null && !Array.isArray(value);
}

function stringRecord(value) {
  return Object.values(value).every((entry) => typeof entry === 'string' && entry.length > 0);
}

/** Converts BCP 47-style runtime locale names to Chrome's locale directory convention. */
function chromeLocaleName(locale) {
  return locale.replaceAll('-', '_');
}
